# Generated by Django 4.0.2 on 2022-11-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=255)),
                ('token_symbol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.CharField(max_length=45)),
                ('address_to', models.CharField(max_length=45)),
                ('date_time', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('contract_address', models.CharField(max_length=45)),
            ],
        ),
    ]
